### PR TITLE
Update component.yaml to kfp v2 sdk

### PR DESCRIPTION
**Pull request by yhwang**
Update component.yaml to kfp v2 compatible. In v2,
you need to declare the data type for all of the input/output
arguments.

Signed-off-by: Yihong Wang <yh.wang@ibm.com>

### CODE REVIEW

**Comment by Tomcli** [comment]
So KFP is working on a new v2 design that requires few extra fields from its components. Part of the requirements is to specify the input/output parameter type for all the KFP components for the new design. This PR is to address this change.

**Comment by nrkarthikeyan** [comment]
@Tomcli , @yhwang - does this change preserve backward compatibility?

**Comment by Tomcli** [comment]
> @Tomcli , @yhwang - does this change preserve backward compatibility?

No, the `type` field was optional in the old KFP version. However, the upcoming v2 KFP version will make the `type` required sometimes next year, so we want to update the AIF360 component to be ready for the new KFP versions.

**Comment by nrkarthikeyan** [comment]
From your response, it seems like `type` field is optional now, but will become mandatory later. So including the `type` field would preserve backward compatibility right? Just making sure it wont break any existing code.

**Comment by Tomcli** [comment]
> From your response, it seems like `type` field is optional now, but will become mandatory later. So including the `type` field would preserve backward compatibility right? Just making sure it wont break any existing code.

yes it will preserve backward compatibility. Nothing will be break from this PR. Sorry I probably didn't interpret your message correctly in my last comment.

**Review by nrkarthikeyan — APPROVED** [review]

**Comment by nrkarthikeyan** [comment]
Ok approved and merged.

**Comment by Tomcli** [comment]
thanks @nrkarthikeyan

**Pull request merged**
