### PR TITLE
Solving second part of issue #381

### PR DESCRIPTION
**Pull request by ivesulca**
Updating notebooks demo_reject_option_classification.ipynb and monthly_bee_datasets_metrics.ipynb

### CODE REVIEW

**Comment by anupamamurthi** [comment]
Looks great - CI should pass. @hoffmansc please review it one more time and merge it. LGTM!

**Comment by anupamamurthi** [comment]
Can you add a "Signed-off-by" tag to the description

**Review by anupamamurthi — APPROVED** [review]
Missing signature - rest lgtm

**Comment by ivesulca** [comment]
Hi Anu, I've just added the "Signed-off by" tag to my commit description now. Thanks.

**Review by hoffmansc — APPROVED** [review]

**Pull request merged**
