### PR TITLE
Add python 3.10 for testing in ci.yml

### LINKED ISSUE #364: Test with Python 3.10 in CI
Add 3.10 to list of python versions in [ci.yml](https://github.com/Trusted-AI/AIF360/blob/master/.github/workflows/ci.yml)

### PR DESCRIPTION
**Pull request by hakimamarullah**
Resolve #364

### CODE REVIEW

**Review by hoffmansc — CHANGES_REQUESTED** [review]
can you do the same for the R builds?

**Comment by hakimamarullah** [comment]
Sure. I'll fix it soon. Thank you

**Comment by hoffmansc** [comment]
Looks like it's getting converted to a float. I think you just need to wrap it in quotes : `'3.10'`

**Comment by hakimamarullah** [comment]
Thank you for your feedback. I have fixed the error by wrapping it in quotes.

**Review by hoffmansc — APPROVED** [review]

**Pull request merged**
