### PR TITLE
[WIP] Add regression metric

### PR DESCRIPTION
**Pull request by SSaishruthi**
This PR adds regression metric to the toolkit

### CODE REVIEW

**Comment by SSaishruthi** [comment]
@nrkarthikeyan This is a basic skeleton I was thinking. We have a bunch of methods to group datasets and get indexes. I did not use existing methods. Rather created a function explaining the functionality. Can you please take a look and provide suggestions?

**Comment by nrkarthikeyan** [comment]
@SSaishruthi - can you verify the DCO thing and sign off?

**Comment by nrkarthikeyan** [comment]
Can we do this directly on the sklearn version? In that case we can follow the pattern in https://github.com/Trusted-AI/AIF360/blob/master/aif360/sklearn/metrics/metrics.py

Is there any reason why the classical version is needed?

**Comment by nrkarthikeyan** [comment]
One place to start if you want to use the "classic" version is to start with the regression dataset class https://github.com/Trusted-AI/AIF360/blob/master/aif360/datasets/regression_dataset.py and also create a regression metric class similar to https://github.com/Trusted-AI/AIF360/blob/master/aif360/metrics/classification_metric.py

@hoffmansc any thoughts?

**Pull request closed without merging**
